### ISSUE TITLE
Handling Network errors

### ISSUE THREAD

**Issue by hvaddi9** [kairosinc/Kairos-SDK-Android#5]
Hi 

I tried to enroll a face when the network is turned off (Its works perfect when the network is ON). I get a NullPointerException and app crashes. I've put try-catch around enroll method but I it's still the same. Is there a way to handle this exception?

**My Code:**
```

if (requestCode == CAMERA_REQUEST && resultCode == Activity.RESULT_OK) {
            photo = (Bitmap) data.getExtras().get("data");
            String subjectId = nameInput.getText().toString();
            String galleryId = serialNo;
            String selector = "FULL";
            String multipleFaces = "true";
            String minHeadScale = "0.25";
            try {
                myKairos.enroll(photo,
                        subjectId,
                        galleryId,
                        selector,
                        multipleFaces,
                        minHeadScale,
                        listener);
            } catch (JSONException | UnsupportedEncodingException | NullPointerException e ) {
                e.printStackTrace();
            }
        }
```

**Runtime error**
```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.vaddi.hemanth.oyna, PID: 11180
                                                                        java.lang.NullPointerException: Attempt to get length of null array
                                                                            at java.lang.StringFactory.newStringFromBytes(StringFactory.java:45)
                                                                            at com.kairos.Kairos$8.onFailure(Kairos.java:464)
                                                                            at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:319)
                                                                            at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:138)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by coleca** [comment]
Hi,

Unfortunately, the Android SDK is provided as-is.  We cannot offer support for it at this time as we don't have any Android developers on staff right now.  The full source code is provided in the repository on Github, however and we gladly accept pull requests.  

However, the REST API is simple enough that it should be able to be used without the SDK.

**Comment by ghost** [comment]
Hey,
I am using Kairos API for face recognition. FIrstly I enrolled 2 bitmaps and then use recognize method to recognize image. When I am trying to recognize image which has not been enrolled yet... means any third separate image, then this exception is displaying. From onFailure method in Kairos.class file . Please help...

**Comment by coleca** [comment]
Hi,

Unfortunately, the Android SDK is provided as-is. We cannot offer support for it at this time as we don't have any Android developers on staff right now. The full source code is provided in the repository on Github, however and we gladly accept pull requests.

However, the REST API is simple enough that it should be able to be used without the SDK.
